"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
function getNews() {
    return [{
            id: 1,
            date: new Date(2019, 4, 11),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt laoreet ligula ac semper. Proin hendrerit pulvinar erat, vitae bibendum elit sagittis non. Etiam pharetra arcu nulla, ut bibendum dolor maximus id. Mauris dictum eros eget egestas lobortis. Donec finibus nisi at est congue, sed efficitur justo mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sit amet velit non dui placerat vehicula. Aliquam erat volutpat. Nunc sit amet orci rutrum, finibus tortor vitae, mattis dolor. Integer ornare nulla molestie dignissim ornare. Morbi egestas ex ut sodales commodo. Donec eleifend tincidunt leo, eget dictum mi. Donec laoreet mi quis faucibus pellentesque. Nullam lacinia quam ac neque finibus tempus. Etiam pharetra consequat dignissim. Maecenas scelerisque rhoncus dui, in dictum lectus fermentum ut.'
        }, {
            id: 2,
            date: new Date(2019, 3, 12),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt laoreet ligula ac semper. Proin hendrerit pulvinar erat, vitae bibendum elit sagittis non. Etiam pharetra arcu nulla, ut bibendum dolor maximus id. Mauris dictum eros eget egestas lobortis. Donec finibus nisi at est congue, sed efficitur justo mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sit amet velit non dui placerat vehicula. Aliquam erat volutpat. Nunc sit amet orci rutrum, finibus tortor vitae, mattis dolor. Integer ornare nulla molestie dignissim ornare. Morbi egestas ex ut sodales commodo. Donec eleifend tincidunt leo, eget dictum mi. Donec laoreet mi quis faucibus pellentesque. Nullam lacinia quam ac neque finibus tempus. Etiam pharetra consequat dignissim. Maecenas scelerisque rhoncus dui, in dictum lectus fermentum ut.'
        }, {
            id: 3,
            date: new Date(2019, 1, 3),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt laoreet ligula ac semper. Proin hendrerit pulvinar erat, vitae bibendum elit sagittis non. Etiam pharetra arcu nulla, ut bibendum dolor maximus id. Mauris dictum eros eget egestas lobortis. Donec finibus nisi at est congue, sed efficitur justo mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sit amet velit non dui placerat vehicula. Aliquam erat volutpat. Nunc sit amet orci rutrum, finibus tortor vitae, mattis dolor. Integer ornare nulla molestie dignissim ornare. Morbi egestas ex ut sodales commodo. Donec eleifend tincidunt leo, eget dictum mi. Donec laoreet mi quis faucibus pellentesque. Nullam lacinia quam ac neque finibus tempus. Etiam pharetra consequat dignissim. Maecenas scelerisque rhoncus dui, in dictum lectus fermentum ut.'
        }, {
            id: 4,
            date: new Date(2019, 1, 3),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt laoreet ligula ac semper. Proin hendrerit pulvinar erat, vitae bibendum elit sagittis non. Etiam pharetra arcu nulla, ut bibendum dolor maximus id. Mauris dictum eros eget egestas lobortis. Donec finibus nisi at est congue, sed efficitur justo mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sit amet velit non dui placerat vehicula. Aliquam erat volutpat. Nunc sit amet orci rutrum, finibus tortor vitae, mattis dolor. Integer ornare nulla molestie dignissim ornare. Morbi egestas ex ut sodales commodo. Donec eleifend tincidunt leo, eget dictum mi. Donec laoreet mi quis faucibus pellentesque. Nullam lacinia quam ac neque finibus tempus. Etiam pharetra consequat dignissim. Maecenas scelerisque rhoncus dui, in dictum lectus fermentum ut.'
        }, {
            id: 5,
            date: new Date(2019, 1, 3),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt laoreet ligula ac semper. Proin hendrerit pulvinar erat, vitae bibendum elit sagittis non. Etiam pharetra arcu nulla, ut bibendum dolor maximus id. Mauris dictum eros eget egestas lobortis. Donec finibus nisi at est congue, sed efficitur justo mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sit amet velit non dui placerat vehicula. Aliquam erat volutpat. Nunc sit amet orci rutrum, finibus tortor vitae, mattis dolor. Integer ornare nulla molestie dignissim ornare. Morbi egestas ex ut sodales commodo. Donec eleifend tincidunt leo, eget dictum mi. Donec laoreet mi quis faucibus pellentesque. Nullam lacinia quam ac neque finibus tempus. Etiam pharetra consequat dignissim. Maecenas scelerisque rhoncus dui, in dictum lectus fermentum ut.'
        }, {
            id: 6,
            date: new Date(2019, 1, 3),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt laoreet ligula ac semper. Proin hendrerit pulvinar erat, vitae bibendum elit sagittis non. Etiam pharetra arcu nulla, ut bibendum dolor maximus id. Mauris dictum eros eget egestas lobortis. Donec finibus nisi at est congue, sed efficitur justo mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sit amet velit non dui placerat vehicula. Aliquam erat volutpat. Nunc sit amet orci rutrum, finibus tortor vitae, mattis dolor. Integer ornare nulla molestie dignissim ornare. Morbi egestas ex ut sodales commodo. Donec eleifend tincidunt leo, eget dictum mi. Donec laoreet mi quis faucibus pellentesque. Nullam lacinia quam ac neque finibus tempus. Etiam pharetra consequat dignissim. Maecenas scelerisque rhoncus dui, in dictum lectus fermentum ut.'
        }, {
            id: 7,
            date: new Date(2019, 1, 3),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt laoreet ligula ac semper. Proin hendrerit pulvinar erat, vitae bibendum elit sagittis non. Etiam pharetra arcu nulla, ut bibendum dolor maximus id. Mauris dictum eros eget egestas lobortis. Donec finibus nisi at est congue, sed efficitur justo mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sit amet velit non dui placerat vehicula. Aliquam erat volutpat. Nunc sit amet orci rutrum, finibus tortor vitae, mattis dolor. Integer ornare nulla molestie dignissim ornare. Morbi egestas ex ut sodales commodo. Donec eleifend tincidunt leo, eget dictum mi. Donec laoreet mi quis faucibus pellentesque. Nullam lacinia quam ac neque finibus tempus. Etiam pharetra consequat dignissim. Maecenas scelerisque rhoncus dui, in dictum lectus fermentum ut.'
        }, {
            id: 8,
            date: new Date(2019, 1, 3),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt laoreet ligula ac semper. Proin hendrerit pulvinar erat, vitae bibendum elit sagittis non. Etiam pharetra arcu nulla, ut bibendum dolor maximus id. Mauris dictum eros eget egestas lobortis. Donec finibus nisi at est congue, sed efficitur justo mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sit amet velit non dui placerat vehicula. Aliquam erat volutpat. Nunc sit amet orci rutrum, finibus tortor vitae, mattis dolor. Integer ornare nulla molestie dignissim ornare. Morbi egestas ex ut sodales commodo. Donec eleifend tincidunt leo, eget dictum mi. Donec laoreet mi quis faucibus pellentesque. Nullam lacinia quam ac neque finibus tempus. Etiam pharetra consequat dignissim. Maecenas scelerisque rhoncus dui, in dictum lectus fermentum ut.'
        }, {
            id: 9,
            date: new Date(2019, 1, 3),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt laoreet ligula ac semper. Proin hendrerit pulvinar erat, vitae bibendum elit sagittis non. Etiam pharetra arcu nulla, ut bibendum dolor maximus id. Mauris dictum eros eget egestas lobortis. Donec finibus nisi at est congue, sed efficitur justo mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sit amet velit non dui placerat vehicula. Aliquam erat volutpat. Nunc sit amet orci rutrum, finibus tortor vitae, mattis dolor. Integer ornare nulla molestie dignissim ornare. Morbi egestas ex ut sodales commodo. Donec eleifend tincidunt leo, eget dictum mi. Donec laoreet mi quis faucibus pellentesque. Nullam lacinia quam ac neque finibus tempus. Etiam pharetra consequat dignissim. Maecenas scelerisque rhoncus dui, in dictum lectus fermentum ut.'
        }, {
            id: 10,
            date: new Date(2019, 1, 3),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt laoreet ligula ac semper. Proin hendrerit pulvinar erat, vitae bibendum elit sagittis non. Etiam pharetra arcu nulla, ut bibendum dolor maximus id. Mauris dictum eros eget egestas lobortis. Donec finibus nisi at est congue, sed efficitur justo mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sit amet velit non dui placerat vehicula. Aliquam erat volutpat. Nunc sit amet orci rutrum, finibus tortor vitae, mattis dolor. Integer ornare nulla molestie dignissim ornare. Morbi egestas ex ut sodales commodo. Donec eleifend tincidunt leo, eget dictum mi. Donec laoreet mi quis faucibus pellentesque. Nullam lacinia quam ac neque finibus tempus. Etiam pharetra consequat dignissim. Maecenas scelerisque rhoncus dui, in dictum lectus fermentum ut.'
        }];
}
exports.getNews = getNews;
//# sourceMappingURL=newsService.js.map